@echo off
title Nonaktifkan Remote Desktop Connection
echo Membuka pengaturan Windows ...
"C:\Windows\System32\desk.cpl"
echo Membuka pengaturan Remote Desktop Protocol ^(RDP ^) ...
"C:\Windows\system32\SystemSettingsAdminFlows.exe" RemoteDesktopTurnOffRdp
echo Menutup pengaturan Windows ...
taskkill /F /IM SystemSettings.exe